local telefang_module = {}
--Attack names
telefang_module.Attacks = {
[0] = {Name = "????", Type = "None"},
[1] = {Name = "Ember", Type = "Fire"},
[2] = {Name = "Fireball", Type = "Fire"},
[3] = {Name = "Fire Pillar", Type = "Fire"},
[4] = {Name = "Petit Fire", Type = "Fire"},
[5] = {Name = "Will o' Wisp", Type = "Fire"},
[6] = {Name = "Flame Shot", Type ="Fire" },
[7] = {Name = "Blaze", Type = "Fire"},
[8] = {Name = "Fire Wheel", Type = "Fire"},
[9] = {Name = "Disk Cutter", Type = "Machine"},
[10] = {Name = "Wheel", Type = "Machine"},
[11] = {Name = "Chainsaw", Type = "Machine"},
[12] = {Name = "Drill", Type = "Machine"},
[13] = {Name = "Rocket Punch", Type = "Machine"},
[14] = {Name = "Twin Drill", Type = "Machine"},
[15] = {Name = "Spin Cutter", Type = "Machine"},
[16] = {Name = "Spiral Cut", Type = "Machine"},
[17] = {Name = "Waterfall", Type = "Water"},
[18] = {Name = "Bubble", Type = "Water"},
[19] = {Name = "Rainfall", Type = "Water"},
[20] = {Name = "Water Gun", Type = "Water"},
[21] = {Name = "Wave Crash", Type = "Water"},
[22] = {Name = "Squall", Type = "Water"},
[23] = {Name = "Icicle Drop", Type = "Water"},
[24] = {Name = "Watersprout", Type = "Water"},
[25] = {Name = "Rock Claw", Type = "Rock"},
[26] = {Name = "Rock Roll", Type = "Rock"},
[27] = {Name = "Dust Devil", Type = "Rock"},
[28] = {Name = "Rock Ball", Type = "Rock"},
[29] = {Name = "Rock Slide", Type = "Rock"},
[30] = {Name = "Sand Shot", Type = "Rock"},
[31] = {Name = "Rock Fall", Type = "Rock"},
[32] = {Name = "Petit Quake", Type = "Rock"},
[33] = {Name = "Vaccum Cutter", Type = "Wind"},
[34] = {Name = "Shockwave", Type = "Wind"},
[35] = {Name = "Whirlwind", Type = "Wind"},
[36] = {Name = "Gust", Type = "Wind"},
[37] = {Name = "Wing Beat", Type = "Wind"},
[38] = {Name = "Tornado", Type = "Wind"},
[39] = {Name = "Gale", Type = "Wind"},
[40] = {Name = "Kamaitachi", Type = "Wind"},
[41] = {Name = "Ion Ball", Type = "Electric"},
[42] = {Name = "Static", Type = "Electric"},
[43] = {Name = "Electric Claw", Type = "Electric"},
[44] = {Name = "Discharge", Type = "Electric"},
[45] = {Name = "Electric Shock", Type = "Electric"},
[46] = {Name = "Electric Arrow", Type = "Electric"},
[47] = {Name = "Voltage", Type = "Electric"},
[48] = {Name = "Electric Field", Type = "Electric"},
[49] = {Name = "Claw", Type = "Normal"},
[50] = {Name = "Iron Claw", Type = "Normal"},
[51] = {Name = "Scale Shot", Type = "Normal"},
[52] = {Name = "Ring", Type = "Normal"},
[53] = {Name = "Bite", Type = "Normal"},
[54] = {Name = "Beak", Type = "Normal"},
[55] = {Name = "Kick", Type = "Normal"},
[56] = {Name = "Multi-Kick", Type = "Normal"},
[57] = {Name = "Sabre", Type = "Normal"},
[58] = {Name = "Tail", Type = "Normal"},
[59] = {Name = "Removed (1)", Type = "None"},
[60] = {Name = "Removed (2)", Type = "None"},
[61] = {Name = "Jump", Type = "Normal"},
[62] = {Name = "Tentacle", Type = "Normal"},
[63] = {Name = "Stun Tentacle", Type = "Normal"},
[64] = {Name = "Tackle", Type = "Normal"},
[65] = {Name = "Spit Spray", Type = "Normal"},
[66] = {Name = "Headbutt", Type = "Normal"},
[67] = {Name = "Removed (3)", Type = "None"},
[68] = {Name = "Horn", Type = "Normal"},
[69] = {Name = "Iron Horn", Type = "Normal"},
[70] = {Name = "Wing", Type = "Normal"},
[71] = {Name = "Thorn", Type = "Normal"},
[72] = {Name = "Rush", Type = "Normal"},
[73] = {Name = "Drain", Type = "Normal"},
[74] = {Name = "Bloodsuck", Type = "Normal"},
[75] = {Name = "Strike", Type = "Normal"},
[76] = {Name = "Razor Punch", Type = "Normal"},
[77] = {Name = "Hammer Punch", Type = "Normal"},
[78] = {Name = "Lick", Type = "Normal"},
[79] = {Name = "Needle", Type = "Normal"},
[80] = {Name = "Removed (4)", Type = "None"},
[81] = {Name = "Scissor", Type = "Normal"},
[82] = {Name = "Petals", Type = "Normal"},
[83] = {Name = "Wing Sabre", Type = "Normal"},
[84] = {Name = "Feather Knife", Type = "Normal"},
[85] = {Name = "Sting", Type = "Normal"},
[86] = {Name = "Poison Sting", Type = "Normal"},
[87] = {Name = "Numbing Sting", Type = "Normal"},
[88] = {Name = "Hoof", Type = "Normal"},
[89] = {Name = "Removed (5)", Type = "None"},
[90] = {Name = "Removed (6)", Type = "None"},
[91] = {Name = "Whip", Type = "Normal"},
[92] = {Name = "Denma Wire", Type = "Normal"},
[93] = {Name = "Stomach Acid", Type = "Normal"},
[94] = {Name = "Acid", Type = "Normal"},
[95] = {Name = "Stab", Type = "Normal"},
[96] = {Name = "Multi-Stab", Type = "Normal"},
[97] = {Name = "Ice Rock", Type = "Water"},
[98] = {Name = "Big Wave", Type = "Water"},
[99] = {Name = "Whirlpool", Type = "Water"},
[100] = {Name = "Ice Bullet", Type = "Water"},
[101] = {Name = "Blizzard", Type = "Water"},
[102] = {Name = "Water Pressure", Type = "Water"},
[103] = {Name = "Big Tsunami", Type = "Water"},
[104] = {Name = "Ion Beam", Type = "Electric"},
[105] = {Name = "Petit Bolt", Type = "Electric"},
[106] = {Name = "Plasma Laser", Type = "Electric"},
[107] = {Name = "Lightning Strike", Type = "Electric"},
[108] = {Name = "Thunderstorm", Type = "Electric"},
[109] = {Name = "Mega Bolt", Type = "Electric"},
[110] = {Name = "Electric Prison", Type = "Electric"},
[111] = {Name = "Wart Missile", Type = "Machine"},
[112] = {Name = "Gatling Gun", Type = "Machine"},
[113] = {Name = "Rapid Missile", Type = "Machine"},
[114] = {Name = "Bazooka", Type = "Machine"},
[115] = {Name = "Drill Missile", Type = "Machine"},
[116] = {Name = "Homing Missile", Type = "Machine"},
[117] = {Name = "Bombing Run", Type = "Machine"},
[118] = {Name = "Wave Cutter", Type = "Wind"},
[119] = {Name = "Pulse Wave", Type = "Wind"},
[120] = {Name = "Sandstorm", Type = "Wind"},
[121] = {Name = "Pressure", Type = "Wind"},
[122] = {Name = "Vacuum Hole", Type = "Wind"},
[123] = {Name = "Hurricane", Type = "Wind"},
[124] = {Name = "Black Hole", Type = "Wind"},
[125] = {Name = "Heat Ray", Type = "Fire"},
[126] = {Name = "Petit Burn", Type = "Fire"},
[127] = {Name = "Petit Flame", Type = "Fire"},
[128] = {Name = "Flamethrower", Type = "Fire"},
[129] = {Name = "Fire Breath", Type = "Fire"},
[130] = {Name = "Big Burn", Type = "Fire"},
[131] = {Name = "Removed (7)", Type = "None"},
[132] = {Name = "Bomb Rock", Type = "Rock"},
[133] = {Name = "Petit Rock", Type = "Rock"},
[134] = {Name = "Sand Prison", Type = "Rock"},
[135] = {Name = "Mega Quake", Type = "Rock"},
[136] = {Name = "Mega Rock", Type = "Rock"},
[137] = {Name = "Meteor Drop", Type = "Rock"},
[138] = {Name = "Diamond Rain", Type = "Rock"},
[139] = {Name = "Mushroom Bomb", Type = "Normal"},
[140] = {Name = "Egg Bomb", Type = "Normal"},
[141] = {Name = "Bomb", Type = "Normal"},
[142] = {Name = "Pulse Beam", Type = "Normal"},
[143] = {Name = "Ray Beam", Type = "Normal"},
[144] = {Name = "Blaster", Type = "Normal"},
[145] = {Name = "Suicide Attack", Type = "Normal"},
[146] = {Name = "Silk Shot", Type = "Offence"},
[147] = {Name = "Sticky Goo", Type = "Offence"},
[148] = {Name = "Smokescreen", Type = "Offence"},
[149] = {Name = "Flash", Type = "Offence"},
[150] = {Name = "Dust Cloud", Type = "Offence"},
[151] = {Name = "Recover", Type = "Defence"},
[152] = {Name = "Restore", Type = "Defence"},
[153] = {Name = "Shout", Type = "Offence"},
[154] = {Name = "Stare", Type = "Offence"},
[155] = {Name = "Glare", Type = "Offence"},
[156] = {Name = "Quick Step", Type = "Defence"},
[157] = {Name = "Speed Up", Type = "Defence"},
[158] = {Name = "Charge", Type = "Defence"},
[159] = {Name = "Full Charge", Type = "Defence"},
[160] = {Name = "Ultrasonic", Type = "Offence"},
[161] = {Name = "Curse Song", Type = "Offence"},
[162] = {Name = "Iron Defense", Type = "Defence"},
[163] = {Name = "Poison", Type = "Normal"},
[164] = {Name = "Poison Gas", Type = "Normal"},
[165] = {Name = "Stun Gas", Type = "Offence"},
[166] = {Name = "Cure", Type = "Defence"},
[167] = {Name = "Awaken", Type = "Defence"},
[168] = {Name = "Roar", Type = "Offence"},
[169] = {Name = "Heat Wave", Type = "Offence"},
[170] = {Name = "Shriek", Type = "Offence"},
[171] = {Name = "Chill", Type = "Offence"},
[172] = {Name = "Sleep Gas", Type = "Offence"},
[173] = {Name = "Lullaby", Type = "Offence"},
[174] = {Name = "Focus", Type = "Defence"},
[175] = {Name = "Denma Barrier", Type = "Defence"},
[176] = {Name = "Brace", Type = "Defence"},
[177] = {Name = "Cheer", Type = "Defence"},
[178] = {Name = "Defend", Type = "Defence"},
[179] = {Name = "Shield", Type = "Defence"},
[180] = {Name = "Bless", Type = "Defence"},
[181] = {Name = "Meditate", Type = "Defence"},
[182] = {Name = "Dig", Type = "Defence"},
[183] = {Name = "Dive", Type = "Defence"},
[184] = {Name = "Fly", Type = "Defence"},
[185] = {Name = "Evade", Type = "Defence"},
[186] = {Name = "Spore Cloud", Type = "Defence"},
[187] = {Name = "Taunt", Type = "Offence"},
[188] = {Name = "Provoke", Type = "Offence"},
[189] = {Name = "Denma Seal", Type = "Offence"},
[190] = {Name = "Denma Drain", Type = "Offence"},
[191] = {Name = "Death Song", Type = "Offence"},
[192] = {Name = "Energy Break", Type = "Offence"},
[193] = {Name = "Mega Break", Type = "Offence"},
[194] = {Name = "Count Down", Type = "Offence"},
[195] = {Name = "Strawberry Kiss", Type = "Defence"},
[196] = {Name = "Injection Plug", Type = "Machine"},
[197] = {Name = "Deflation Spiral", Type = "Normal"},
[198] = {Name = "Healing Spring", Type = "Defence"},
[199] = {Name = "Nove Smasher", Type = "Fire"},
[223] = {Name = "Poisoned", Type = "None"}
}

--List of Denjuu by names, sorted by Index
telefang_module.Denjuu = {
[0] = {Name = "Muscovy (Basic)", Photo = 15},
[1] = {Name = "Muscovy (Natural)", Photo = 16},
[2] = {Name = "Muscovy (Aquatic)", Photo = 17},
[3] = {Name = "Major (Basic)", Photo = 176},
[4] = {Name = "Major (Grassland)", Photo = 177},
[5] = {Name = "Fraby (Basic)", Photo = 18},
[6] = {Name = "Fraby (Mountain)", Photo = 19},
[7] = {Name = "Fraby (Sky)", Photo = 20},
[8] = {Name = "Kagu (Basic)", Photo = 21},
[9] = {Name = "Kagu (Natural)", Photo = 22},
[10] = {Name = "Purchera (Basic)", Photo = 23}, 
[11] = {Name = "Purchera (Sky)", Photo = 24},
[12] = {Name = "Purchera (Forest)", Photo = 25},
[13] = {Name = "Mentalis (Basic)", Photo = 26},
[14] = {Name = "Mentalis (Natural)", Photo = 27},
[15] = {Name = "Mentalis (Forest)", Photo = 28},
[16] = {Name = "Mentalis (Grassland)", Photo = 29},
[17] = {Name = "Karinota (Basic)", Photo = 30},
[18] = {Name = "Karinota (Grassland)", Photo = 31},
[19] = {Name = "Karinota (Mountain)", Photo = 32},
[20] = {Name = "Chukar (Basic)", Photo = 37}, 
[21] = {Name = "Chukar (Natural)", Photo = 38},
[22] = {Name = "Chukar (Mountain)", Photo = 39},
[23] = {Name = "Chukar (Aquatic)", Photo = 40},
[24] = {Name = "Laperouse (Basic)", Photo = 33},
[25] = {Name = "Laperouse  (Natural)", Photo = 34},
[26] = {Name = "Laperouse (Desert)", Photo = 35},
[27] = {Name = "Laperouse (Grassland)", Photo = 36},
[28] = {Name = "Anpipitto (Basic)", Photo = 41},
[29] = {Name = "Anpipitto (Sky)", Photo = 42},
[30] = {Name = "Anpipitto (Desert)", Photo = 43}, 
[31] = {Name = "Ruficors (Basic)", Photo = 44},
[32] = {Name = "Ruficors (Grassland)", Photo = 45},
[33] = {Name = "Ruficors (Aquatic)", Photo = 46},
[34] = {Name = "Cotta (Basic)", Photo = 47},
[35] = {Name = "Cotta (Natural)", Photo = 48},
[36] = {Name = "Cotta (Desert)", Photo = 49},
[37] = {Name = "Rupicola (Basic)", Photo = 178},
[38] = {Name = "Rupicola (Grassland)", Photo = 179},
[39] = {Name = "Rupicola (Sky)", Photo = 180},
[40] = {Name = "Willcock (Basic)", Photo = 50}, 
[41] = {Name = "Willcock (Natural)", Photo = 51},
[42] = {Name = "Willcock (Forest)", Photo = 52},
[43] = {Name = "Skrippa (Basic)", Photo = 53},
[44] = {Name = "Skrippa (Aquatic)", Photo = 54},
[45] = {Name = "Cabot (Basic)", Photo = 55},
[46] = {Name = "Cabot (Natural)", Photo = 56},
[47] = {Name = "Makyuretto (Basic)", Photo = 57},
[48] = {Name = "Makyuretto (Natural)", Photo = 58},
[49] = {Name = "Makyuretto (Grassland)", Photo = 59},
[50] = {Name = "Makyuretto (Forest)", Photo = 60}, 
[51] = {Name = "Coronet (Basic)", Photo = 61},
[52] = {Name = "Coronet (Aquatic)", Photo = 62},
[53] = {Name = "Coronet (Grassland)", Photo = 63},
[54] = {Name = "Tataupa (Basic)", Photo = 64},
[55] = {Name = "Tataupa (Desert)", Photo = 65},
[56] = {Name = "Tataupa (Forest)", Photo = 66},
[57] = {Name = "Chigomozu (Basic)", Photo = 67},
[58] = {Name = "Chigomozu (Natural)", Photo = 68},
[59] = {Name = "Koikaru (Basic)", Photo = 69},
[60] = {Name = "Koikaru (Natural)", Photo = 70}, 
[61] = {Name = "Koikaru (Forest)", Photo = 71},
[62] = {Name = "Pewee (Basic)", Photo = 72},
[63] = {Name = "Pewee (Natural)", Photo = 73},
[64] = {Name = "Pewee (Aquatic)", Photo = 74},
[65] = {Name = "Pewee (Mountain)", Photo = 75},
[66] = {Name = "Chapmani (Basic)", Photo = 76},
[67] = {Name = "Chapmani (Natural)", Photo = 77},
[68] = {Name = "Hyuming (Basic)", Photo = 78},
[69] = {Name = "Hyuming (Natural)", Photo = 79},
[70] = {Name = "Hyuming (Mountain)", Photo = 80}, 
[71] = {Name = "Pamirio (Basic)", Photo = 81},
[72] = {Name = "Pamirio (Natural)", Photo = 82},
[73] = {Name = "Pamirio (Sky)", Photo = 83},
[74] = {Name = "Pamirio (Desert)", Photo = 84},
[75] = {Name = "Mistashi (Basic)", Photo = 85},
[76] = {Name = "Mistashi (Forest)", Photo = 86},
[77] = {Name = "Mistashi (Aquatic)", Photo = 87},
[78] = {Name = "Parrotto (Basic)", Photo = 181},
[79] = {Name = "Parrotto (Natural)", Photo = 182},
[80] = {Name = "Nebularia (Basic)", Photo = 183}, 
[81] = {Name = "Nebularia (Natural)", Photo = 184},
[82] = {Name = "Granti (Basic)", Photo = 185},
[83] = {Name = "Granti (Nautral)", Photo = 186},
[84] = {Name = "Granti (Desert)", Photo = 187},
[85] = {Name = "Penelope (Basic)", Photo = 88},
[86] = {Name = "Penelope (Aquatic)", Photo = 89},
[87] = {Name = "Penelope (Mountain)", Photo = 90},
[88] = {Name = "Ardea (Basic)", Photo = 188},
[89] = {Name = "Ardea (Natural)", Photo = 189},
[90] = {Name = "Ardea (Forest)", Photo = 190}, 
[91] = {Name = "Cerator (Basic)", Photo = 191},
[92] = {Name = "Cerator (Natural)", Photo = 192},
[93] = {Name = "Cerator (Mountain)", Photo = 193},
[94] = {Name = "Alpina (Basic)", Photo = 91},
[95] = {Name = "Alpina (Natural)", Photo = 92},
[96] = {Name = "Alpina (Aquatic)", Photo = 93},
[97] = {Name = "Alpina (Sky)", Photo = 94},
[98] = {Name = "Isuka (Basic)", Photo = 194},
[99] = {Name = "Isuka (Grassland)", Photo = 195},
[100] = {Name = "Bicolour (Basic)", Photo = 95}, 
[101] = {Name = "Bicolour (Natural)", Photo = 96},
[102] = {Name = "Hermit (Basic)", Photo = 97},
[103] = {Name = "Hermit (Natural)", Photo = 98},
[104] = {Name = "Hermit (Desert)", Photo = 99},
[105] = {Name = "Hermit (Grassland)", Photo = 100},
[106] = {Name = "Phoebe (Basic)", Photo = 101},
[107] = {Name = "Phoebe (Aquatic)", Photo = 102},
[108] = {Name = "Phoebe (Desert)", Photo = 103},
[109] = {Name = "Blossom (Basic)", Photo = 196},
[110] = {Name = "Blossom (Mountain)", Photo = 197}, 
[111] = {Name = "Rabricol (Basic)", Photo = 104},
[112] = {Name = "Rabricol (Natural)", Photo = 105},
[113] = {Name = "Rabricol (Aquatic)", Photo = 106},
[114] = {Name = "Demerus (Basic)", Photo = 107},
[115] = {Name = "Demerus (Natural)", Photo = 108},
[116] = {Name = "Demerus (Desert)", Photo = 109},
[117] = {Name = "Sparsa (Basic)", Photo = 110},
[118] = {Name = "Sparsa (Natural)", Photo = 111},
[119] = {Name = "Sparsa (Forest)", Photo = 112},
[120] = {Name = "Purprea (Basic)", Photo = 113}, 
[121] = {Name = "Purprea (Sky)", Photo = 114},
[122] = {Name = "Purprea (Grassland)", Photo = 115},
[123] = {Name = "Etopirika (Basic)", Photo = 116},
[124] = {Name = "Etopirika (Natural)", Photo = 117},
[125] = {Name = "Etopirika (Forest)", Photo = 118},
[126] = {Name = "Regulus (Basic)", Photo = 119},
[127] = {Name = "Regulus (Desert)", Photo = 120},
[128] = {Name = "Regulus (Sky)", Photo = 121},
[129] = {Name = "Akretto (Basic)", Photo = 122},
[130] = {Name = "Akretto (Natural)", Photo = 123}, 
[131] = {Name = "Akretto (Grassland)", Photo = 124},
[132] = {Name = "Akretto (Mountain)", Photo = 125},
[133] = {Name = "Seiran (Basic)", Photo = 198},
[134] = {Name = "Seiran (Mountain)", Photo = 199},
[135] = {Name = "Tectus (Basic)", Photo = 126},
[136] = {Name = "Tectus (Natural)", Photo = 127},
[137] = {Name = "Serrata (Basic)", Photo = 128},
[138] = {Name = "Serrata (Sky)", Photo = 129},
[139] = {Name = "Serrata (Forest)", Photo = 130},
[140] = {Name = "Kaya (T2)", Photo = 131}, 
[141] = {Name = "Beebalm (T2)", Photo = 132},
[142] = {Name = "Easydog (T2)", Photo = 133},
[143] = {Name = "Ruscus (T2)", Photo = 134},
[144] = {Name = "Ryuuguu (T2)", Photo = 135},
[145] = {Name = "Kanzou (T2)", Photo = 136},
[146] = {Name = "Ornithogalum (T2)", Photo = 137},
[147] = {Name = "Teletel (T2)", Photo = 138},
[148] = {Name = "Dendel (T2)", Photo = 139},
[149] = {Name = "Suguri (T2)", Photo = 140},
[150] = {Name = "Suguline (T2)", Photo = 141}, 
[151] = {Name = "Saiguliger (T2)", Photo = 142},
[152] = {Name = "Punica (T2)", Photo = 143},
[153] = {Name = "Punisto (T2)", Photo = 144},
[154] = {Name = "Oshe (T2)", Photo = 145},
[155] = {Name = "Barriarm (T2)", Photo = 146},
[156] = {Name = "Bashou (T2)", Photo = 147},
[157] = {Name = "Gentiana (T2)", Photo = 148},
[158] = {Name = "Gonum (T2)", Photo = 149},
[159] = {Name = "Gust (T2)", Photo = 150},
[160] = {Name = "Storm (T2)", Photo = 151}, 
[161] = {Name = "Tsunonasu (T2)", Photo = 152},
[162] = {Name = "Gigagigearth (T2)", Photo = 153},
[163] = {Name = "Liriope (T2)", Photo = 154},
[164] = {Name = "Lirimonarch (T2)", Photo = 155},
[165] = {Name = "Waratah (T2)", Photo = 156},
[166] = {Name = "Enteiou (T2)", Photo = 157},
[167] = {Name = "Gumi (T2)", Photo = 158},
[168] = {Name = "Gymnos (T2)", Photo = 159},
[169] = {Name = "Gymbaron (T2)", Photo = 160},
[170] = {Name = "Gymzyrus (T2)", Photo = 161}, 
[171] = {Name = "Gymzatan (T2)", Photo = 162},
[172] = {Name = "Angios (T2)", Photo = 163},
[173] = {Name = "Angigorgo (T2)", Photo = 164},
[174] = {Name = "Angipower (T2)", Photo = 165},
[175] = {Name = "Angioros (T2)", Photo = 166},
[176] = {Name = "Fungus (T2)", Photo = 167},
[177] = {Name = "Fungwar (T2)", Photo = 168},
[178] = {Name = "Funboost (T2)", Photo = 169},
[179] = {Name = "Funblade (T2)", Photo = 170},
[180] = {Name = "Rex (Basic)", Photo = 0}, 
[181] = {Name = "Rex (Natural-1)", Photo = 1},
[182] = {Name = "Rex (Desert)", Photo = 2},
[183] = {Name = "Rex (Forest)", Photo = 3},
[184] = {Name = "Rex (Natural-2)", Photo = 4},
[185] = {Name = "Doon (Basic)", Photo = 5},
[186] = {Name = "Doon (Natural-1)", Photo = 6},
[187] = {Name = "Doon (Sky)", Photo = 7},
[188] = {Name = "Doon (Aquatic)", Photo = 8},
[189] = {Name = "Doon (Natural-2)", Photo = 9},
[190] = {Name = "Gyuun (Basic)", Photo = 10}, 
[191] = {Name = "Gyuun (Natural-1)", Photo = 11},
[192] = {Name = "Gyuun (Aquatic)", Photo = 12},
[193] = {Name = "Gyuun (Forest)", Photo = 13},
[194] = {Name = "Gyuun (Natural-2)", Photo = 14},
[195] = {Name = "Diablos (Basic)", Photo = 171},
[196] = {Name = "Diablos (Natural-1)", Photo = 172},
[197] = {Name = "Diablos (Mountain)", Photo = 173},
[198] = {Name = "Diablos (Grassland)", Photo = 174},
[199] = {Name = "Diablos (Natural-2)", Photo = 175}
}

--List of items, sorted by index
telefang_module.Items = {
--Support Items
[0] = {Name = "Herb", Type = "Support", Sell = 9},
[1] = {Name = "Pills", Type = "Support", Sell = 48},
[2] = {Name = "Berry", Type = "Support", Sell = 90},
[3] = {Name = "Strange Water", Type = "Support", Sell = 180},
[4] = {Name = "Healing Gas", Type = "Support", Sell = 60},
[5] = {Name = "Recovery Gas", Type = "Support", Sell = 300},
[6] = {Name = "Pickled Berry", Type = "Support", Sell = 480},
[7] = {Name = "Rainbow Water", Type = "Support", Sell = 600},
[8] = {Name = "HP Capsule", Type = "Support", Sell = 600},
[9] = {Name = "SP Capsule", Type = "Support", Sell = 600},
[10] = {Name = "AT Capsule", Type = "Support", Sell = 600},
[11] = {Name = "DF Capsule", Type = "Support", Sell = 600},
[12] = {Name = "DP Capsule", Type = "Support", Sell = 600},
[13] = {Name = "Antidote", Type = "Support", Sell = 18},
[14] = {Name = "Alarm Clock", Type = "Support", Sell = 30},
[15] = {Name = "Ointment", Type = "Support", Sell = 24},
[16] = {Name = "Jewel", Type = "Support", Sell = 48},
[17] = {Name = "Eyedrops", Type = "Support", Sell = 36},
[18] = {Name = "Mystery Bud", Type = "Support", Sell = 300},
[19] = {Name = "Mystery Flower", Type = "Support", Sell = 300},
[20] = {Name = "Flower Extract", Type = "Support", Sell = 600},
[21] = {Name = "Flower Honey", Type = "Support", Sell = 600},
[22] = {Name = "Denma Cookie", Type = "Support", Sell = 60},
[23] = {Name = "Denma Aid", Type = "Support", Sell = 120},
[24] = {Name = "Denma Drink", Type = "Support", Sell = 480},
[25] = {Name = "Dummy 3", Type = "Support", Sell = 60},
[26] = {Name = "Dummy 4", Type = "Support", Sell = 60},
[27] = {Name = "Dummy 5", Type = "Support", Sell = 60},
[28] = {Name = "Dummy 6", Type = "Support", Sell = 60},
[29] = {Name = "Dummy 7", Type = "Support", Sell = 60},
---Equip Items
[30] = {Name = "Blue Charm", Type = "Equip", Sell = 1200},
[31] = {Name = "Green Charm", Type = "Equip", Sell = 3000},
[32] = {Name = "Red Charm", Type = "Equip", Sell = 9000},
[33] = {Name = "Blue Ring", Type = "Equip", Sell = 1200},
[34] = {Name = "Green Ring", Type = "Equip", Sell = 3000},
[35] = {Name = "Red Ring", Type = "Equip", Sell = 9000},
[36] = {Name = "Blue Bracelet", Type = "Equip", Sell = 1200},
[37] = {Name = "Green Bracelet", Type = "Equip", Sell = 3000},
[38] = {Name = "Red Bracelet", Type = "Equip", Sell = 9000},
[39] = {Name = "Blue Crown", Type = "Equip", Sell = 1200},
[40] = {Name = "Green Crown", Type = "Equip", Sell = 3000},
[41] = {Name = "Red Crown", Type = "Equip", Sell = 9000},
[42] = {Name = "Blue Crystal", Type = "Equip", Sell = 1200},
[43] = {Name = "Green Crystal", Type = "Equip", Sell = 3000},
[44] = {Name = "Red Crystal", Type = "Equip", Sell = 9000},
[45] = {Name = "Blue Pendant", Type = "Equip", Sell = 1200},
[46] = {Name = "Green Pendant", Type = "Equip", Sell = 3000},
[47] = {Name = "Red Pendant", Type = "Equip", Sell = 9000},
[48] = {Name = "Blue Earrings", Type = "Equip", Sell = 1200},
[49] = {Name = "Green Earrings", Type = "Equip", Sell = 3000},
[50] = {Name = "Red Earrings", Type = "Equip", Sell = 9000},
[51] = {Name = "Blue Bandana", Type = "Equip", Sell = 1200},
[52] = {Name = "Green Bandana", Type = "Equip", Sell = 3000},
[53] = {Name = "Red Bandana", Type = "Equip", Sell = 9000},
[54] = {Name = "Dummy 8", Type = "Equip", Sell = 3000},
[55] = {Name = "Dummy 9", Type = "Equip", Sell = 3000},
[56] = {Name = "Dummy 10", Type = "Equip", Sell = 3000},
[57] = {Name = "Dummy 11", Type = "Equip", Sell = 3000},
[58] = {Name = "Dummy 12", Type = "Equip", Sell = 3000},
[59] = {Name = "Dummy 13", Type = "Equip", Sell = 3000},
[60] = {Name = "Dummy 14", Type = "Equip", Sell = 3000},
[61] = {Name = "Dummy 15", Type = "Equip", Sell = 3000},
--Evolution Items
[62] = {Name = "Nails", Type = "Evolution", Sell = 60, EType = "Mountain"},
[63] = {Name = "Bracket", Type = "Evolution", Sell = 72, EType = "Mountain"},
[64] = {Name = "Kite String", Type = "Evolution", Sell = 60, EType = "Forest"},
[65] = {Name = "Rope", Type = "Evolution", Sell = 72, EType = "Forest"},
[66] = {Name = "Paper Knife", Type = "Evolution", Sell = 60, EType = "Grassland"},
[67] = {Name = "Survival Knife", Type = "Evolution", Sell = 72, EType = "Grassland"},
[68] = {Name = "Flashlight", Type = "Evolution", Sell = 120, EType = "Mountain"},
[69] = {Name = "Searchlight", Type = "Evolution", Sell = 150, EType = "Mountain"},
[70] = {Name = "Lighter", Type = "Evolution", Sell = 60, EType = "Desert"},
[71] = {Name = "Gas Burner", Type = "Evolution", Sell = 72, EType = "Desert"},
[72] = {Name = "Dryer", Type = "Evolution", Sell = 120, EType = "Desert"},
[73] = {Name = "Stove", Type = "Evolution", Sell = 150, EType = "Desert"},
[74] = {Name = "Mirror", Type = "Evolution", Sell = 288, EType = "Desert"},
[75] = {Name = "Solar Panel", Type = "Evolution", Sell = 336, EType = "Desert"},
[76] = {Name = "Boom Box", Type = "Evolution", Sell = 126, EType = "Forest"},
[77] = {Name = "Stereo", Type = "Evolution", Sell = 138, EType = "Forest"},
[78] = {Name = "Revolver", Type = "Evolution", Sell = 120, EType = "Grassland"},
[79] = {Name = "Machine Gun", Type = "Evolution", Sell = 150, EType = "Grassland"},
[80] = {Name = "Saw", Type = "Evolution", Sell = 312, EType = "Forest"},
[81] = {Name = "Chainsaw", Type = "Evolution", Sell = 366, EType = "Forest"},
[82] = {Name = "Camera", Type = "Evolution", Sell = 630, EType = "Forest"},
[83] = {Name = "Video Camera", Type = "Evolution", Sell = 780, EType = "Forest"},
[84] = {Name = "Canteen", Type = "Evolution", Sell = 750, EType = "Desert"},
[85] = {Name = "Jerrycan", Type = "Evolution", Sell = 780, EType = "Desert"},
[86] = {Name = "Shovel", Type = "Evolution", Sell = 300, EType = "Mountain"},
[87] = {Name = "Crane", Type = "Evolution", Sell = 360, EType = "Mountain"},
[88] = {Name = "Engine", Type = "Evolution", Sell = 60, EType = "Sky"},
[89] = {Name = "Prop Engine", Type = "Evolution", Sell = 78, EType = "Sky"},
[90] = {Name = "Firecracker", Type = "Evolution", Sell = 120, EType = "Sky"},
[91] = {Name = "Dynamite", Type = "Evolution", Sell = 120, EType = "Sky"},
[92] = {Name = "Mixer", Type = "Evolution", Sell = 60, EType = "Aquatic"},
[93] = {Name = "Washer", Type = "Evolution", Sell = 60, EType = "Aquatic"},
[94] = {Name = "Parachute", Type = "Evolution", Sell = 300, EType = "Sky"},
[95] = {Name = "Glider", Type = "Evolution", Sell = 330, EType = "Sky"},
[96] = {Name = "Oxygen Tank", Type = "Evolution", Sell = 132, EType = "Aquatic"},
[97] = {Name = "Gas Tank", Type = "Evolution", Sell = 126, EType = "Aquatic"},
[98] = {Name = "Oar", Type = "Evolution", Sell = 300, EType = "Aquatic"},
[99] = {Name = "Propellar", Type = "Evolution", Sell = 390, EType = "Aquatic"},
[100] = {Name = "Fireworks", Type = "Evolution", Sell = 720, EType = "Sky"},
[101] = {Name = "Missile", Type = "Evolution", Sell = 900, EType = "Sky"},
[102] = {Name = "Lunatium", Type = "Evolution", Sell = 720, EType = "Mountain"},
[103] = {Name = "Titanium", Type = "Evolution", Sell = 900, EType = "Mountain"},
[104] = {Name = "Electric Fan", Type = "Evolution", Sell = 300, EType = "Grassland"},
[105] = {Name = "Air Conditioner", Type = "Evolution", Sell = 360, EType = "Grassland"},
[106] = {Name = "Sickle", Type = "Evolution", Sell = 720, EType = "Grassland"},
[107] = {Name = "Lawn Mower", Type = "Evolution", Sell = 960, EType = "Grassland"},
[108] = {Name = "Squirt Gun", Type = "Evolution", Sell = 720, EType = "Aquatic"},
[109] = {Name = "Pump", Type = "Evolution", Sell = 660, EType = "Aquatic"},
[110] = {Name = "Dummy 16", Type = "Evolution", Sell = 666, EType = "None"},
[111] = {Name = "Dummy 17", Type = "Evolution", Sell = 0, EType = "None"},
[112] = {Name = "Dummy 18", Type = "Evolution", Sell = 0, EType = "None"},
[113] = {Name = "Dummy 19", Type = "Evolution", Sell = 0, EType = "None"},
[114] = {Name = "Dummy 20", Type = "Evolution", Sell = 0, EType = "None"},
[115] = {Name = "Dummy 21", Type = "Evolution", Sell = 0, EType = "None"},
--Event Items
[116] = {Name = "Chakor's Ring", Type = "Event", Sell = 0},
[117] = {Name = "Crown", Type = "Event", Sell = 0},
[118] = {Name = "Antenna Seed", Type = "Event", Sell = 0},
[119] = {Name = "Key", Type = "Event", Sell = 0},
[120] = {Name = "Strange Object", Type = "Event", Sell = 0},
[121] = {Name = "Strange Object", Type = "Event", Sell = 0},
[122] = {Name = "Strange Object", Type = "Event", Sell = 0},
[123] = {Name = "Map", Type = "Event", Sell = 0},
[124] = {Name = "D-Shot", Type = "Event", Sell = 0},
[125] = {Name = "Water Ball", Type = "Event", Sell = 0},
[126] = {Name = "License", Type = "Event", Sell = 0},
[127] = {Name = "None", Type = "Event", Sell = 0},
}

--List of map ids
telefang_module.Map = {
[0] = "Takedama Forest",
[1] = "Tokaribe Field",
[2] = "Chiawata Forest",
[3] = "Chiawata Forest",
[4] = "Meribaro Forest",
[5] = "Meribaro Forest",
[6] = "Kiwatora Field",
[7] = "Kiwatora Field",
[8] = "Uraani Forest",
[9] = "Uraani Forest",
[10] = "Uraani Tides",
[11] = "Uraani Forest",
[12] = "Uraani Forest",
[13] = "Uraani Forest",
[14] = "Uraani Forest",
[15] = "Kufumoku Mountain",
[16] = "Takedama Village",
[17] = "Tokaribe Village",
[18] = "Meribaro Village",
[19] = "Kiwatora Village",
[20] = "Bijinia Village",
[21] = "Takedama Cave",
[22] = "Takedama Cave",
[23] = "Kufumoku Mountain",
[24] = "Kufumoku Mountain",
[25] = "Hiero Loophole",
[26] = "Hiero Loophole",
[27] = "Hiero Loophole",
[28] = "Hiero Loophole",
[29] = "Ujichichi Mountain",
[30] = "Ujichichi Mountain",
[31] = "Ujichichi Mountain",
[32] = "Ujichichi Mountain",
[33] = "Ujichichi Mountain",
[34] = "Ujichichi Mountain",
[35] = "Ujichichi Mountain",
[36] = "Ujichichi Mountain",
[37] = "Ujichichi Mountain",
[38] = "Ujichichi Mountain",
[39] = "Takedama Village",
[40] = "Takedama Village",
[41] = "Takedama Village",
[42] = "Takedama Village",
[43] = "Tokaribe Village",
[44] = "Meribaro Village",
[45] = "Kiwatora Village",
[46] = "Bijinia Village",
[47] = "Chiawata Village",
[48] = "Human World",
[49] = "Chiawata Cave",
[50] = "Chiawata Cave",
[51] = "Chiawata Cave",
[52] = "Chiawata Cave",
[53] = "Chiawata Cave",
[54] = "Uraani Cave",
[55] = "Uraani Cave",
[56] = "Uraani Cave",
[57] = "Uraani Cave",
[58] = "Uraani Cave",
[59] = "Uraani Cave",
[60] = "Uraani Cave",
[61] = "Uraani Cave",
[62] = "Uraani Cave",
[63] = "Barusuta Forest",
[64] = "Barusuta Forest",
[65] = "Barusuta Forest",
[66] = "Barusuta Forest",
[67] = "Barusuta Forest",
[68] = "Barusuta Forest",
[69] = "Barusuta Forest",
[70] = "Barusuta Forest",
[71] = "Helchika Desert",
[72] = "Helchika Desert",
[73] = "Helchika Desert",
[74] = "Helchika Desert",
[75] = "Bijinia Desert",
[76] = "Bijinia Desert",
[77] = "Bijinia Desert",
[78] = "Bijinia Desert",
[79] = "Tokaribe Village",
[80] = "Meribaro Village",
[81] = "Kiwatora Village",
[82] = "Kiwatora Coast",
[83] = "Tokaribe Coast",
[84] = "Tokaribe Coast",
[85] = "Tokaribe Field",
[86] = "Tokaribe Coast",
[87] = "Chiawata Village",
[88] = "Uraani Village",
[89] = "Ujichichi Mountain",
[90] = "Ujichichi Mountain",
[91] = "Ujichichi Mountain",
[92] = "Ujichichi Mountain",
[93] = "Meribaro Village",
[94] = "Tokaribe Village",
[95] = "Kiwatora Village",
[96] = "Helchika Village",
[97] = "Bijinia Village",
[98] = "Bandit's Hideout",
[99] = "Bandit's Hideout",
[100] = "Bandit's Hideout",
[101] = "Bandit's Hideout",
[102] = "Bandit's Hideout",
[103] = "Bandit's Hideout",
[104] = "Bandit's Hideout",
[105] = "Uraani Cave",
[106] = "Kamishino Ruins",
[107] = "Kamishino Ruins",
[108] = "Kamishino Ruins",
[109] = "Kamishino Ruins",
[110] = "Kamishino Ruins",
[111] = "Kamishino Ruins",
[112] = "Kamishino Ruins",
[113] = "Kamishino Ruins",
[114] = "Kamishino Ruins",
[115] = "Kamishino Ruins",
[116] = "Karatsumu Cave",
[117] = "Karatsumu Cave",
[118] = "Karatsumu Cave",
[119] = "Karatsumu Cave",
[120] = "Karatsumu Cave",
[121] = "Karatsumu Cave",
[122] = "Karatsumu Cave",
[123] = "Karatsumu Cave",
[124] = "Karatsumu Cave",
[125] = "Karatsumu Cave",
[126] = "Karatsumu Cave",
[127] = "Karatsumu Cave",
[128] = "Human World",
[129] = "Helchika Village",
[130] = "Helchika Village",
[131] = "Bijinia Village",
[132] = "Bijinia Village",
[133] = "Chiawata Forest",
[134] = "Human World",
[135] = "Tekku Sea",
[136] = "Holy Land Iasuka",
[137] = "Tekku Sea",
[138] = "Takedama Village",
[139] = "Chiawata Village",
[140] = "Helchika Village",
[141] = "Uraani Village",
[142] = "Holy Land Iasuka",
[143] = "Human World",
[144] = "Holy Land Iasuka",
[145] = "Holy Land Iasuka",
[146] = "Holy Land Iasuka",
[147] = "Holy Land Iasuka",
[148] = "Holy Land Iasuka",
[149] = "Holy Land Iasuka",
[150] = "Holy Land Iasuka",
[151] = "Holy Land Iasuka",
[152] = "Holy Land Iasuka",
[153] = "Holy Land Iasuka",
[154] = "Holy Land Iasuka",
[155] = "Holy Land Iasuka",
[156] = "Holy Land Iasuka",
[157] = "Holy Land Iasuka",
[158] = "Holy Land Iasuka",
[159] = "Holy Land Iasuka",
[160] = "Holy Land Iasuka",
[161] = "Holy Land Iasuka",
[162] = "Holy Land Iasuka",
[163] = "Holy Land Iasuka",
[164] = "Holy Land Iasuka",
[165] = "Human World",
[166] = "Uraani Village",
[167] = "Chiawata Village",
[168] = "Uraani Village",
[169] = "Tokaribe Village",
[170] = "Meribaro Village"
}


--Addresses I'm interested regarding speed version
telefang_module.Speed = {
State = 	0x042C,
Counter = 	0x0840,
Win = 		0x2870,
Boss = 		0x2888,
Damage = 	0x2A0B,
Move = 		0x2B06,
Miss = 		0x2C14,
Battle_State = 0x2C16,
Crit = 		0x2C22,
Battle_Event_Timer = 0x2BA0,
Recruit = 	0x4102,
Team = 		{0x4140,0x4178,0x41B0}, --+0x15 to get turns it takes
Enemy = 	{0x41F0,0x4228,0x4260}, --+0x15 to get turns it takes
Music = 	0x4AE2,	--Seems like it's the background music ID; can use this to check if in battle
Money = 	0x4CF4,
Player_X = 	0x4CF8,
Player_Y = 	0x4CFC,
Story = 	0x4DD7,
Map = 		0x4F90,
Talk = 		0x50F4, --State of dialogue
RNG1 =		0x5E08,
RNG2 = 		0x5E10
}

--Addresses I'm interested regarding power version
telefang_module.Power = {
State = 	0x043C,
Counter = 	0x0850,
Win = 		0x2880,
Boss = 		0x2898,
Damage = 	0x2A1B,
Miss = 		0x2C24,
Battle_State = 0x2C26,
Crit = 		0x2C32,
Battle_Event_Timer = 0x2BB0,
Recruit = 	0x4112,
Team = 		{0x4150,0x4188,0x41C0}, --+0x15 to get turns it takes
Enemy = 	{0x4200,0x4238,0x4270},--+0x15 to get turns it takes
Music = 	0x4AF2,
Money = 	0x4D04,
Player_X = 	0x4D08,
Player_Y = 	0x4D0C,
Move = 		0x2B16,
Story = 	0x4DE7,
Map = 		0x4FA0,
Talk = 		0x5104, --State of dialogue
RNG1 = 		0x5E18,
RNG2 = 		0x5E20
}
return telefang_module
